# Management
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
